-- Set display order for price list items to match exact sequence
-- This ensures the price list appears in the correct order as specified

-- Add display_order column if it doesn't exist
ALTER TABLE price_list_items 
  ADD COLUMN IF NOT EXISTS display_order INTEGER;

-- Set display order for each item in exact sequence
UPDATE price_list_items SET display_order = 1 WHERE item_no = '2PBP-8';
UPDATE price_list_items SET display_order = 2 WHERE item_no = '2PCF-9';
UPDATE price_list_items SET display_order = 3 WHERE item_no = '2PBP-10';
UPDATE price_list_items SET display_order = 4 WHERE item_no = '2PBPXW-10';
UPDATE price_list_items SET display_order = 5 WHERE item_no = '2PCXL-10';
UPDATE price_list_items SET display_order = 6 WHERE item_no = '2PDOA-10';
UPDATE price_list_items SET display_order = 7 WHERE item_no = '2PBP-12';
UPDATE price_list_items SET display_order = 8 WHERE item_no = '2PCHD-12';
UPDATE price_list_items SET display_order = 9 WHERE item_no = '2PCHD-15';
UPDATE price_list_items SET display_order = 10 WHERE item_no = '2 Post Accessories';
UPDATE price_list_items SET display_order = 11 WHERE item_no = '4PTA-6';
UPDATE price_list_items SET display_order = 12 WHERE item_no = '4PTA-3';
UPDATE price_list_items SET display_order = 13 WHERE item_no = '8PTA';
UPDATE price_list_items SET display_order = 14 WHERE item_no = '2PC';
UPDATE price_list_items SET display_order = 15 WHERE item_no = '4 POST LIFTS';
UPDATE price_list_items SET display_order = 16 WHERE item_no = '4HML-9';
UPDATE price_list_items SET display_order = 17 WHERE item_no = 'HUMBIL-9';
UPDATE price_list_items SET display_order = 18 WHERE item_no = 'HXBC-10';
UPDATE price_list_items SET display_order = 19 WHERE item_no = 'HUMBIL-10';
UPDATE price_list_items SET display_order = 20 WHERE item_no = '4PXL-10';
UPDATE price_list_items SET display_order = 21 WHERE item_no = '4PXXW-10';
UPDATE price_list_items SET display_order = 22 WHERE item_no = '4PHXL-11';
UPDATE price_list_items SET display_order = 23 WHERE item_no = '4PHXL-12';
UPDATE price_list_items SET display_order = 24 WHERE item_no = '4PHXLA-14';
UPDATE price_list_items SET display_order = 25 WHERE item_no = '4PHXLA-15';
UPDATE price_list_items SET display_order = 26 WHERE item_no = '4P2XI';
UPDATE price_list_items SET display_order = 27 WHERE item_no = '4PHXOL-22';
UPDATE price_list_items SET display_order = 28 WHERE item_no = '4PHXOL-22';
UPDATE price_list_items SET display_order = 29 WHERE item_no = '4PHXL-27';
UPDATE price_list_items SET display_order = 30 WHERE item_no = '4PHXLA-27';
UPDATE price_list_items SET display_order = 31 WHERE item_no = '4PHXLA-33';
UPDATE price_list_items SET display_order = 32 WHERE item_no = '4PHIM-HLR-series';
UPDATE price_list_items SET display_order = 33 WHERE item_no = 'FBC14';
UPDATE price_list_items SET display_order = 34 WHERE item_no = 'HXCC-6';
UPDATE price_list_items SET display_order = 35 WHERE item_no = 'HLC-14/ V2RC1-7';
UPDATE price_list_items SET display_order = 36 WHERE item_no = 'HR-10';
UPDATE price_list_items SET display_order = 37 WHERE item_no = '4PRO-9';
UPDATE price_list_items SET display_order = 38 WHERE item_no = '4PHXD-RJ';
UPDATE price_list_items SET display_order = 39 WHERE item_no = '4PTT';
UPDATE price_list_items SET display_order = 40 WHERE item_no = 'RED';
UPDATE price_list_items SET display_order = 41 WHERE item_no = 'EBAR-2';
UPDATE price_list_items SET display_order = 42 WHERE item_no = 'XMACHINE';
UPDATE price_list_items SET display_order = 43 WHERE item_no = 'ALT-11-15';
UPDATE price_list_items SET display_order = 44 WHERE item_no = 'SSAT-11-15';
UPDATE price_list_items SET display_order = 45 WHERE item_no = '4PDT';
UPDATE price_list_items SET display_order = 46 WHERE item_no = 'MA-8APLFM';
UPDATE price_list_items SET display_order = 47 WHERE item_no = 'FB-9PLFM';
UPDATE price_list_items SET display_order = 48 WHERE item_no = 'HR-10PLFM';
UPDATE price_list_items SET display_order = 49 WHERE item_no = 'XW-10PLFM';
UPDATE price_list_items SET display_order = 50 WHERE item_no = 'APLFM-12';
UPDATE price_list_items SET display_order = 51 WHERE item_no = 'RED';
UPDATE price_list_items SET display_order = 52 WHERE item_no = 'RED';
UPDATE price_list_items SET display_order = 53 WHERE item_no = 'SCISSOR LIFTS';
UPDATE price_list_items SET display_order = 54 WHERE item_no = 'MRS-6';
UPDATE price_list_items SET display_order = 55 WHERE item_no = 'MRSL-7S';
UPDATE price_list_items SET display_order = 56 WHERE item_no = 'PRSL-7B';
UPDATE price_list_items SET display_order = 57 WHERE item_no = 'RED';
UPDATE price_list_items SET display_order = 58 WHERE item_no = 'Tire Machines';
UPDATE price_list_items SET display_order = 59 WHERE item_no = 'T999-E';
UPDATE price_list_items SET display_order = 60 WHERE item_no = 'T650';
UPDATE price_list_items SET display_order = 61 WHERE item_no = 'T620';
UPDATE price_list_items SET display_order = 62 WHERE item_no = 'Accessories';
UPDATE price_list_items SET display_order = 63 WHERE item_no = 'MCA-1';
UPDATE price_list_items SET display_order = 64 WHERE item_no = 'Wheel Balancers';
UPDATE price_list_items SET display_order = 65 WHERE item_no = 'WB20';
UPDATE price_list_items SET display_order = 66 WHERE item_no = 'WB10';
UPDATE price_list_items SET display_order = 67 WHERE item_no = 'W800';
UPDATE price_list_items SET display_order = 68 WHERE item_no = 'Alignment Machines';
UPDATE price_list_items SET display_order = 69 WHERE item_no = 'A5800';
UPDATE price_list_items SET display_order = 70 WHERE item_no = 'ACB-1';
UPDATE price_list_items SET display_order = 71 WHERE item_no = 'SHOP EQUIPMENT';
UPDATE price_list_items SET display_order = 72 WHERE item_no = 'R-45';
UPDATE price_list_items SET display_order = 73 WHERE item_no = 'R-30';
UPDATE price_list_items SET display_order = 74 WHERE item_no = 'Accessories';
UPDATE price_list_items SET display_order = 75 WHERE item_no = 'RT-1';
UPDATE price_list_items SET display_order = 76 WHERE item_no = 'MOTORCYCLE LIFTS';
UPDATE price_list_items SET display_order = 77 WHERE item_no = 'HCWM-15';
UPDATE price_list_items SET display_order = 78 WHERE item_no = 'Accessories';
UPDATE price_list_items SET display_order = 79 WHERE item_no = 'MCWC-1G/1SS';
UPDATE price_list_items SET display_order = 80 WHERE item_no = 'HDMJ-1';
UPDATE price_list_items SET display_order = 81 WHERE item_no = 'HCMC-2';
UPDATE price_list_items SET display_order = 82 WHERE item_no = 'MOBILE';
UPDATE price_list_items SET display_order = 83 WHERE item_no = 'BNDL-PDF15';
UPDATE price_list_items SET display_order = 84 WHERE item_no = 'BXBDL-FO-11';
UPDATE price_list_items SET display_order = 85 WHERE item_no = 'BNDL-PAC-4';
UPDATE price_list_items SET display_order = 86 WHERE item_no = 'BXBDL-WS-1';
UPDATE price_list_items SET display_order = 87 WHERE item_no = 'RED';
UPDATE price_list_items SET display_order = 88 WHERE item_no = 'APU-1';
UPDATE price_list_items SET display_order = 89 WHERE item_no = 'AS-7X';
UPDATE price_list_items SET display_order = 90 WHERE item_no = 'UHS-750';
UPDATE price_list_items SET display_order = 91 WHERE item_no = 'AE-430';
UPDATE price_list_items SET display_order = 92 WHERE item_no = 'OD-7170';
UPDATE price_list_items SET display_order = 93 WHERE item_no = 'OD-733AB';
UPDATE price_list_items SET display_order = 94 WHERE item_no = 'OD-3198';
UPDATE price_list_items SET display_order = 95 WHERE item_no = 'HLO-7 / T1-707';
UPDATE price_list_items SET display_order = 96 WHERE item_no = 'T1-1101A / T12718';
UPDATE price_list_items SET display_order = 97 WHERE item_no = 'AW-32';
UPDATE price_list_items SET display_order = 98 WHERE item_no = 'AW-32-G';
UPDATE price_list_items SET display_order = 99 WHERE item_no = 'HPI-220';
UPDATE price_list_items SET display_order = 100 WHERE item_no = 'RED';

-- Create index on display_order for efficient ordering
CREATE INDEX IF NOT EXISTS idx_price_list_items_display_order ON price_list_items(display_order);
